# Generated by Django 6.0.2 on 2026-06-02 15:34

import django.db.models.deletion
import django_lifecycle.mixins
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lex_app', '0002_delete_asoftestmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalScheduledCalculation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('target_object_id', models.CharField(max_length=255)),
                ('dedupe_tag', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FIRED', 'FIRED'), ('CANCELLED', 'CANCELLED'), ('MISSED', 'MISSED')], db_index=True, default='PENDING', max_length=20)),
                ('periodic_task_name', models.CharField(blank=True, default='', max_length=255)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, help_text='When this fact ceased to be true in the real world. NULL means it is still the current truth.', null=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical scheduled calculation',
                'verbose_name_plural': 'historical scheduled calculations',
                'ordering': ('-valid_from', '-history_id'),
                'get_latest_by': ('valid_from', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetaHistoricalScheduledCalculation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('target_object_id', models.CharField(max_length=255)),
                ('dedupe_tag', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FIRED', 'FIRED'), ('CANCELLED', 'CANCELLED'), ('MISSED', 'MISSED')], db_index=True, default='PENDING', max_length=20)),
                ('periodic_task_name', models.CharField(blank=True, default='', max_length=255)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('history_id', models.IntegerField(blank=True, db_index=True)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, help_text='When this fact ceased to be true in the real world. NULL means it is still the current truth.', null=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('meta_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_from', models.DateTimeField(db_index=True)),
                ('sys_to', models.DateTimeField(blank=True, default=None, help_text='When this system record was superseded.', null=True)),
                ('meta_history_change_reason', models.CharField(max_length=100, null=True)),
                ('meta_history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('meta_task_name', models.CharField(blank=True, help_text='Name of the scheduled PeriodicTask.', max_length=255, null=True, unique=True)),
                ('meta_task_status', models.CharField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=20)),
            ],
            options={
                'verbose_name': 'historical historical scheduled calculation',
                'verbose_name_plural': 'historical historical scheduled calculations',
                'db_table': 'lex_app_scheduledcalculation_meta_history',
                'ordering': ('-sys_from', '-meta_history_id'),
                'get_latest_by': ('sys_from', 'meta_history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduledCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.TextField(blank=True, editable=False, null=True)),
                ('edited_by', models.TextField(blank=True, editable=False, null=True)),
                ('target_object_id', models.CharField(max_length=255)),
                ('dedupe_tag', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FIRED', 'FIRED'), ('CANCELLED', 'CANCELLED'), ('MISSED', 'MISSED')], db_index=True, default='PENDING', max_length=20)),
                ('periodic_task_name', models.CharField(blank=True, default='', max_length=255)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='historicalscheduledcalculation',
            name='history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscheduledcalculation',
            name='target_content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='metahistoricalscheduledcalculation',
            name='history_object',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lex_app.historicalscheduledcalculation'),
        ),
        migrations.AddField(
            model_name='metahistoricalscheduledcalculation',
            name='history_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metahistoricalscheduledcalculation',
            name='meta_history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metahistoricalscheduledcalculation',
            name='target_content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='scheduledcalculation',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='scheduledcalculation',
            index=models.Index(fields=['target_content_type', 'target_object_id', 'dedupe_tag', 'status'], name='lex_sched_dedupe_idx'),
        ),
    ]
