"""
Cluster: design system — the vendored LEX tokens.

``lex/lex_app/design_system/lex_tokens.py`` is generated by
``@excellencecloudgmbh/lex-tokens`` and copied in verbatim, so there is no logic
here to unit-test. What these scenarios protect is the failure that can actually
reach a customer: a *regeneration* that is fresh but structurally wrong for the
Streamlit host that consumes it.

CI already diffs the vendored file against the artefact attached to the
lex-tokens GitHub release (``frontend_build.yml``) — that catches staleness.
These catch shape:

* **mode symmetry** — a token group present in one mode but not the other
  renders a half-themed host, dark mode falling back to browser defaults
  mid-page.
* **alias fidelity** — the 16 flat constants (``NAVY``, ``ERROR``, …) are the
  facade Streamlit code imports. A value moving in ``TOKENS`` without its alias
  following leaves the host painting last release's brand while the design
  system believes it shipped.
* **the WCAG values that shipped** — the accessibility release moved
  ``status.error`` off ``#e74c3c`` (white-on-error measured 3.82:1, below the
  4.5:1 the brand guideline mandates) and the control radius 10px → 8px. A
  palette rollback should fail loudly, not regress contrast quietly.
* **CSS validity** — these are interpolated straight into stylesheets, where a
  malformed value is simply ignored and the element renders unstyled.

Plain pytest functions rather than ``SimpleTestCase``: the module under test is
pure data with no Django import, so these stay runnable both under the lex CLI
and under bare ``pytest`` (which this repo configures with ``-p no:django``).
"""

from __future__ import annotations

import re

import pytest

from lex.lex_app.design_system import lex_tokens

pytestmark = pytest.mark.design_system

CSS_COLOUR = re.compile(
    r"^(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)|linear-gradient\([^)]*\)|transparent|color-mix\([^)]*\))$"
)


def test_both_modes_are_present() -> None:
    assert set(lex_tokens.TOKENS) == {"light", "dark"}


def test_light_and_dark_carry_the_same_groups() -> None:
    assert set(lex_tokens.TOKENS["light"]) == set(lex_tokens.TOKENS["dark"])


def test_light_and_dark_colour_groups_match() -> None:
    assert set(lex_tokens.TOKENS["light"]["color"]) == set(lex_tokens.TOKENS["dark"]["color"])


def test_flat_aliases_agree_with_the_token_tree() -> None:
    light = lex_tokens.TOKENS["light"]
    assert lex_tokens.NAVY == light["color"]["navy"]["700"]
    assert lex_tokens.NAVY_DEEP == light["color"]["navy"]["deep"]
    assert lex_tokens.NAVY_LIGHT == light["color"]["navy"]["light"]
    assert lex_tokens.TEAL == light["color"]["teal"]["500"]
    assert lex_tokens.TEAL_DEEP == light["color"]["teal"]["600"]
    assert lex_tokens.TEAL_LIGHT == light["color"]["teal"]["light"]
    assert lex_tokens.BG == light["color"]["bg"]["canvas"]
    assert lex_tokens.SURFACE == light["color"]["bg"]["surface"]
    assert lex_tokens.INK == light["color"]["text"]["primary"]
    assert lex_tokens.MUTED == light["color"]["text"]["muted"]
    assert lex_tokens.ERROR == light["color"]["status"]["error"]
    assert lex_tokens.WARNING == light["color"]["status"]["warning"]
    assert lex_tokens.SUCCESS == light["color"]["status"]["success"]
    assert lex_tokens.INFO == light["color"]["status"]["info"]
    assert lex_tokens.HEADER_GRADIENT == light["gradient"]["header"]
    assert lex_tokens.CTA_GRADIENT == light["gradient"]["cta"]


def test_wcag_release_values_are_the_ones_that_shipped() -> None:
    assert lex_tokens.TOKENS["light"]["color"]["status"]["error"] == "#d32f2f"
    assert lex_tokens.TOKENS["dark"]["color"]["status"]["error"] == "#d32f2f"
    assert lex_tokens.TOKENS["light"]["radius"]["control"] == "8px"


def test_every_colour_value_is_a_usable_css_colour() -> None:
    bad = []
    for mode in ("light", "dark"):
        for group, entries in lex_tokens.TOKENS[mode]["color"].items():
            if not isinstance(entries, dict):
                continue
            for key, value in entries.items():
                if isinstance(value, str) and not CSS_COLOUR.match(value):
                    bad.append(f"{mode}.color.{group}.{key} = {value!r}")
    assert not bad, "non-CSS colour values: " + ", ".join(bad)


def test_star_export_exposes_the_aliases() -> None:
    """``design_system/__init__.py`` re-exports with ``*``; a rename would drop these silently."""
    from lex.lex_app import design_system

    for name in ("NAVY", "TEAL", "ERROR", "TOKENS", "HEADER_GRADIENT"):
        assert hasattr(design_system, name), name
