"""LEX Design System — vendored design tokens for the Streamlit host.

`lex_tokens.py` is GENERATED by @excellencecloudgmbh/lex-tokens (the LEX
Design System token pipeline) and vendored here so the host styles from the
same source of truth as the React apps. Do not hand-edit — it is refreshed
by the frontend_build workflow from the lex-design-system release assets.

Vendored from: @excellencecloudgmbh/lex-tokens@0.2.0-rc.0
"""

from lex.lex_app.design_system import lex_tokens

__all__ = ["lex_tokens"]
