"""LEX Design System tokens for the Streamlit host.

`lex_tokens` is VENDORED, not a dependency: the Streamlit host installs from PyPI and cannot
reach the private GitHub Packages registry the JS packages live in. It is generated by
`@excellencecloudgmbh/lex-tokens` and copied in verbatim — never hand-edit it. CI checks it
against the artefact attached to the lex-tokens GitHub release (see frontend_build.yml); to
refresh, copy `packages/tokens/dist/python/lex_tokens.py` from a released design-system build.
"""

from .lex_tokens import *  # noqa: F401,F403
