"""Guards for the vendored LEX design tokens.

`lex_tokens.py` is generated by `@excellencecloudgmbh/lex-tokens` and copied in verbatim, so there
is no logic here to unit-test. What these tests protect is the thing that actually breaks: a
*regeneration* that silently changes shape or drifts from the design system.

CI already diffs the vendored file against the artefact attached to the lex-tokens GitHub release
(see frontend_build.yml) — that catches staleness. These tests catch the complementary failure: a
file that is fresh but structurally wrong for the Streamlit host that consumes it.
"""

import re

from lex.lex_app.design_system import lex_tokens as t

CSS_COLOUR = re.compile(
    r"^(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)|linear-gradient\([^)]*\)|transparent|color-mix\([^)]*\))$"
)


def test_both_modes_are_present():
    assert set(t.TOKENS) == {"light", "dark"}


def test_light_and_dark_carry_the_same_groups():
    """A group present in one mode but not the other means a half-themed host."""
    assert set(t.TOKENS["light"]) == set(t.TOKENS["dark"])


def test_light_and_dark_colour_groups_match():
    assert set(t.TOKENS["light"]["color"]) == set(t.TOKENS["dark"]["color"])


def test_flat_aliases_agree_with_the_token_tree():
    """The convenience constants are a hand-maintained facade over TOKENS.

    They are what Streamlit code actually imports, so a regeneration that moves a value without
    updating the alias would leave the host rendering last release's brand.
    """
    light = t.TOKENS["light"]
    assert t.NAVY == light["color"]["navy"]["700"]
    assert t.NAVY_DEEP == light["color"]["navy"]["deep"]
    assert t.NAVY_LIGHT == light["color"]["navy"]["light"]
    assert t.TEAL == light["color"]["teal"]["500"]
    assert t.TEAL_DEEP == light["color"]["teal"]["600"]
    assert t.TEAL_LIGHT == light["color"]["teal"]["light"]
    assert t.BG == light["color"]["bg"]["canvas"]
    assert t.SURFACE == light["color"]["bg"]["surface"]
    assert t.INK == light["color"]["text"]["primary"]
    assert t.MUTED == light["color"]["text"]["muted"]
    assert t.ERROR == light["color"]["status"]["error"]
    assert t.WARNING == light["color"]["status"]["warning"]
    assert t.SUCCESS == light["color"]["status"]["success"]
    assert t.INFO == light["color"]["status"]["info"]
    assert t.HEADER_GRADIENT == light["gradient"]["header"]
    assert t.CTA_GRADIENT == light["gradient"]["cta"]


def test_phase_8_wcag_values_are_the_ones_that_shipped():
    """Pins the accessibility release so a rollback to the old palette is loud, not silent.

    The WCAG AA pass moved status.error off #e74c3c (white-on-error was 3.82:1) and the control
    radius from 10px to 8px. Both are visible brand decisions worth a failing test.
    """
    assert t.TOKENS["light"]["color"]["status"]["error"] == "#d32f2f"
    assert t.TOKENS["dark"]["color"]["status"]["error"] == "#d32f2f"
    assert t.TOKENS["light"]["radius"]["control"] == "8px"


def test_every_colour_value_is_a_usable_css_colour():
    """Streamlit interpolates these straight into CSS, so a malformed value fails silently there."""
    bad = []
    for mode in ("light", "dark"):
        for group, entries in t.TOKENS[mode]["color"].items():
            if not isinstance(entries, dict):
                continue
            for key, value in entries.items():
                if isinstance(value, str) and not CSS_COLOUR.match(value):
                    bad.append(f"{mode}.color.{group}.{key} = {value!r}")
    assert not bad, "non-CSS colour values: " + ", ".join(bad)


def test_star_export_exposes_the_aliases():
    """`design_system/__init__.py` re-exports with `*`; underscore-prefixed names would vanish."""
    from lex.lex_app import design_system

    for name in ("NAVY", "TEAL", "ERROR", "TOKENS", "HEADER_GRADIENT"):
        assert hasattr(design_system, name), name
