# This is a basic workflow to help you get started with Actions

name: ci-master-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: azure/login@v1.1
      with:
        login-server: lexreg.azurecr.io
        creds: ${{ secrets.AZURE_CREDENTIALS_GLOBAL }}
        
    - uses: azure/docker-login@v1
      with:
        login-server: lexreg.azurecr.io
        username: ${{ secrets.AZURE_LEXREG_USERNAME_GLOBAL }}
        password: ${{ secrets.AZURE_LEXREG_PASSWORD_GLOBAL }}

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-docker.pkg.dev

    # Build the master branch
    - name: Run docker build
      run: docker build --no-cache -t django_process_admin:latest -f ./build/Dockerfile .
    
    # Tag the image in the right way so it can be pushed to Azure
    - name: Run docker tag latest
      run: docker tag django_process_admin:latest lexreg.azurecr.io/django_process_admin:latest

    # Tag the image also with master to follow conventions
    - name: Run docker tag master
      run: docker tag django_process_admin:latest lexreg.azurecr.io/django_process_admin:master
    
    # Push the latest tag
    - name: Run docker push latest
      run: docker push lexreg.azurecr.io/django_process_admin:latest

    # Push the master tag
    - name: Run docker push master
      run: docker push lexreg.azurecr.io/django_process_admin:master

    # Tag for GCP
    - name: Run docker tag
      run: docker tag django_process_admin:latest europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:master

    # Push to GCP
    - name: Run docker push
      run: docker push europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:master

    # Tag for GCP
    - name: Run docker tag
      run: docker tag django_process_admin:latest europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:latest

    # Push to GCP
    - name: Run docker push
      run: docker push europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:latest
