# Generated by Django 6.0.3 on 2026-05-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legacy_data", "0003_legacylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyDynamicDefaultCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Legacy default_cache",
                "verbose_name_plural": "Legacy default_cache",
                "db_table": "default_cache",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyDynamicGenericAppModificationrestrictedmodelexample",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Legacy generic_app_modificationrestrictedmodelexample",
                "verbose_name_plural": "Legacy generic_app_modificationrestrictedmodelexample",
                "db_table": "generic_app_modificationrestrictedmodelexample",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyDynamicOidcCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Legacy oidc_cache",
                "verbose_name_plural": "Legacy oidc_cache",
                "db_table": "oidc_cache",
                "managed": False,
            },
        ),
    ]
