# Generated by Django 6.0.2 on 2026-05-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legacy_data", "0004_legacydynamicdefaultcache_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyDynamicDefaultCache",
        ),
        migrations.DeleteModel(
            name="LegacyDynamicGenericAppModificationrestrictedmodelexample",
        ),
        migrations.DeleteModel(
            name="LegacyDynamicOidcCache",
        ),
    ]
