name: Retag Image

on:
  push:
    tags:
      - "v*"

jobs:
  build-dpag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION}}
    steps:
      - uses: actions/checkout@v2

      - id: "gcloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          create_credentials_file: false

      # This example uses the docker login action
      - uses: "docker/login-action@v1"
        with:
          registry: "europe-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.gcloud-auth.outputs.access_token }}"

      - name: Read and output sha and version
        id: version
        run: |
          echo "VERSION=v${GITHUB_REF##*v}" >> $GITHUB_ENV
          echo "VERSION=v${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"
          echo "SHA=${GITHUB_SHA::7}"  >> $GITHUB_ENV
          echo "SHA=${GITHUB_SHA::7}"  >> "$GITHUB_OUTPUT"

      - name: Retag image
        run: |
          gcloud artifacts docker tags add europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:${{ env.SHA }} europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/django_process_admin:${{ env.VERSION }}

  trigger-deploy-to-test:
    needs: [build-dpag]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout instance-controller-deployment
        uses: actions/checkout@v2
        with:
          repository: LundIT/instance-controller-deployment
          token: ${{ secrets.PAT }}
          path: ./instance-controller-deployment
          ref: develop

      - name: Update version in versions file
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'touch temp.json && jq ".versions.django_process_admin_generic = \"${{ needs.build-dpag.outputs.version }}\"" instance-controller-deployment/terraform/ic-test-application/versions.auto.tfvars.json > temp.json && mv temp.json instance-controller-deployment/terraform/ic-test-application/versions.auto.tfvars.json'

      - name: Push version update
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          cd instance-controller-deployment
          git pull
          git add terraform/ic-test-application/versions.auto.tfvars.json
          git commit -m "[DPAG][$(git rev-parse --short "$GITHUB_SHA")] Push version ${{ needs.build-dpag.outputs.version }}"
          git pull
          git push origin develop
          ls -a
