# Generated by Django 6.0.3 on 2026-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0002_auditlog_created_at_auditlog_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="edited_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="auditlogstatus",
            name="edited_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
