# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0003_alter_auditlog_created_at_alter_auditlog_edited_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="auditlogstatus",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="auditlogstatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="auditlogstatus",
            name="edited_by",
        ),
    ]
