# Generated by Django 6.0.3 on 2026-05-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0005_calculationlog_calculationid_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="calculation_id",
            field=models.TextField(
                blank=True, default="test_id", null=True, verbose_name="Calculation Log"
            ),
        ),
    ]
