"""Cluster 1z: LEX Design System tokens — vendored Python module.

Intent
------
``lex/lex_app/design_system/lex_tokens.py`` is the Python-side copy of the
LEX token set (generated by ``@excellencecloudgmbh/lex-tokens``).  Because the
Streamlit host installs from PyPI and cannot reach the private GitHub Packages
registry, this file is **vendored** — nothing else notices when it goes stale.

A customer building a Streamlit view over lex-app depends on these constants
to produce correct colours, spacing, and typography.  The tests here pin what
the framework *guarantees*:

1. The module is importable without error.
2. Top-level shorthand constants (NAVY, TEAL, ERROR, …) exist and are
   non-empty strings.
3. The TOKENS dict provides both ``"light"`` and ``"dark"`` mode keys, each
   with the standard structural sections (color, radius, spacing, gradient,
   fontFamily, fontWeight, elevation, …).
4. Phase 8 mandatory values are present in both modes:

   * ``TOKENS[mode]["color"]["status"]["error"]`` == ``"#d32f2f"``
     (the Phase 8 ERROR revision — the old value was darker).
   * ``TOKENS[mode]["color"]["text"]["onWarning"]`` exists
     (new role introduced in Phase 8; must not be absent or empty).

5. The top-level ``ERROR`` constant (shorthand alias) matches the light-mode
   status token — consumers must not have to know about modes for basic use.
6. The top-level ``NAVY`` / ``TEAL`` constants are consistent with the
   light-mode colour palette entries.
7. Both modes share the same top-level structural sections
   (colour-completeness regression gate: a regeneration that drops a whole
   section must not go undetected).

Scenarios: 1.211–1.217.
"""

from __future__ import annotations

import importlib
from unittest import TestCase

import pytest

pytestmark = pytest.mark.init


class TestCluster01z_LexTokens(TestCase):
    """Regression gate for the vendored LEX Design System token module."""

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------

    @classmethod
    def setUpClass(cls):
        cls.mod = importlib.import_module("lex.lex_app.design_system.lex_tokens")

    # ------------------------------------------------------------------
    # Scenario 1.211 — module is importable
    # ------------------------------------------------------------------

    def test_1_211_module_importable(self):
        """Scenario 1.211: lex.lex_app.design_system.lex_tokens imports cleanly.

        Given  the framework is installed (editable or as a wheel)
        When   ``importlib.import_module("lex.lex_app.design_system.lex_tokens")``
               is called
        Then   no exception is raised and the returned module is not None.
        """
        self.assertIsNotNone(self.mod)

    # ------------------------------------------------------------------
    # Scenario 1.212 — top-level shorthand constants present and non-empty
    # ------------------------------------------------------------------

    def test_1_212_top_level_constants_present(self):
        """Scenario 1.212: Top-level shorthand constants are all non-empty strings.

        Given  the module is imported
        When   each documented shorthand constant is accessed
        Then   it is a non-empty string (not None, not an empty string).

        Covers: NAVY, NAVY_DEEP, NAVY_LIGHT, TEAL, TEAL_DEEP, TEAL_LIGHT,
                OCEAN, BG, SURFACE, INK, MUTED, BORDER, ERROR, WARNING,
                SUCCESS, INFO, HEADER_GRADIENT, CTA_GRADIENT,
                FONT_HEADING, FONT_BODY.
        """
        constants = [
            "NAVY", "NAVY_DEEP", "NAVY_LIGHT",
            "TEAL", "TEAL_DEEP", "TEAL_LIGHT",
            "OCEAN", "BG", "SURFACE", "INK", "MUTED", "BORDER",
            "ERROR", "WARNING", "SUCCESS", "INFO",
            "HEADER_GRADIENT", "CTA_GRADIENT",
            "FONT_HEADING", "FONT_BODY",
        ]
        for name in constants:
            with self.subTest(constant=name):
                value = getattr(self.mod, name, None)
                self.assertIsNotNone(value, f"{name} is missing from lex_tokens")
                self.assertIsInstance(value, str, f"{name} must be a string")
                self.assertGreater(len(value), 0, f"{name} must not be empty")

    # ------------------------------------------------------------------
    # Scenario 1.213 — TOKENS dict has light and dark keys with sections
    # ------------------------------------------------------------------

    def test_1_213_tokens_dict_light_and_dark_modes(self):
        """Scenario 1.213: TOKENS dict exposes both 'light' and 'dark' modes.

        Given  the module is imported
        When   the TOKENS attribute is accessed
        Then   it is a dict with at minimum the keys 'light' and 'dark',
               each of whose values is itself a non-empty dict containing
               the core structural sections expected by UI consumers.
        """
        tokens = self.mod.TOKENS
        self.assertIsInstance(tokens, dict)
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                self.assertIn(mode, tokens, f"TOKENS missing '{mode}' mode")
                mode_dict = tokens[mode]
                self.assertIsInstance(mode_dict, dict)
                self.assertGreater(len(mode_dict), 0)

        required_sections = {"color", "radius", "spacing", "gradient", "fontFamily"}
        for mode in ("light", "dark"):
            mode_dict = tokens[mode]
            for section in required_sections:
                with self.subTest(mode=mode, section=section):
                    self.assertIn(
                        section, mode_dict,
                        f"TOKENS['{mode}'] missing section '{section}'"
                    )

    # ------------------------------------------------------------------
    # Scenario 1.214 — Phase 8 ERROR token is #d32f2f in both modes
    # ------------------------------------------------------------------

    def test_1_214_phase8_error_token_value(self):
        """Scenario 1.214: status.error is '#d32f2f' (Phase 8 value) in both modes.

        Given  the module is imported
        When   TOKENS[mode]['color']['status']['error'] is read for each mode
        Then   the value is '#d32f2f'.

        This pins the specific Phase 8 ERROR revision; an accidental regeneration
        with an older token set would produce a different shade and be caught here.
        """
        expected_error = "#d32f2f"
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                actual = self.mod.TOKENS[mode]["color"]["status"]["error"]
                self.assertEqual(
                    actual, expected_error,
                    f"TOKENS['{mode}']['color']['status']['error'] should be "
                    f"'{expected_error}' (Phase 8), got '{actual}'"
                )

    # ------------------------------------------------------------------
    # Scenario 1.215 — Phase 8 onWarning role present in both modes
    # ------------------------------------------------------------------

    def test_1_215_phase8_on_warning_role_exists(self):
        """Scenario 1.215: color.text.onWarning exists and is non-empty in both modes.

        Given  the module is imported
        When   TOKENS[mode]['color']['text']['onWarning'] is accessed
        Then   it is a non-empty string in both 'light' and 'dark' modes.

        onWarning is the new foreground role introduced in Phase 8 for text
        rendered on top of the warning/amber background.  If it were absent,
        consumers would fall back to an undefined colour and accessibility
        contrast would be broken.
        """
        for mode in ("light", "dark"):
            with self.subTest(mode=mode):
                text_section = self.mod.TOKENS[mode]["color"]["text"]
                self.assertIn(
                    "onWarning", text_section,
                    f"TOKENS['{mode}']['color']['text'] missing 'onWarning' (Phase 8 role)"
                )
                value = text_section["onWarning"]
                self.assertIsInstance(value, str)
                self.assertGreater(len(value), 0, "'onWarning' must not be an empty string")

    # ------------------------------------------------------------------
    # Scenario 1.216 — top-level ERROR alias matches light-mode status token
    # ------------------------------------------------------------------

    def test_1_216_top_level_error_alias_matches_tokens(self):
        """Scenario 1.216: top-level ERROR constant matches TOKENS light status.error.

        Given  the module is imported
        When   ERROR is compared with TOKENS['light']['color']['status']['error']
        Then   they are equal.

        Consumers who only need a single colour (e.g. a Streamlit badge) use
        the top-level alias rather than navigating the full dict.  If the alias
        and the token diverge, the two access patterns would produce different
        colours on screen.
        """
        self.assertEqual(
            self.mod.ERROR,
            self.mod.TOKENS["light"]["color"]["status"]["error"],
            "Top-level ERROR constant must match TOKENS['light']['color']['status']['error']"
        )

    # ------------------------------------------------------------------
    # Scenario 1.217 — both modes share the same top-level structural sections
    # ------------------------------------------------------------------

    def test_1_217_both_modes_share_same_top_level_sections(self):
        """Scenario 1.217: light and dark modes have identical top-level section keys.

        Given  the module is imported
        When   the top-level keys of TOKENS['light'] and TOKENS['dark'] are compared
        Then   they are equal (neither mode is missing a section the other provides).

        A regeneration that drops a section from one mode only (e.g. 'dark'
        loses 'elevation') would otherwise go undetected until a dark-mode
        consumer crashes at runtime.
        """
        light_keys = set(self.mod.TOKENS["light"].keys())
        dark_keys = set(self.mod.TOKENS["dark"].keys())
        self.assertEqual(
            light_keys, dark_keys,
            f"Mismatch between light and dark mode sections:\n"
            f"  only in light: {light_keys - dark_keys}\n"
            f"  only in dark:  {dark_keys - light_keys}"
        )
