name: ci-main-pycharm-push

on:
  push:
    tags:
      - "headless-pycharm-v*"
  workflow_dispatch:

jobs:
  build-headless-pycharm:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION}}
    steps:
      - uses: actions/checkout@v2

      - id: "gcloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          create_credentials_file: false

      # This example uses the docker login action
      - uses: "docker/login-action@v1"
        with:
          registry: "europe-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.gcloud-auth.outputs.access_token }}"

      - name: Read and output sha
        id: version
        run: |
          echo "VERSION=v${GITHUB_REF##*v}" >> $GITHUB_ENV
          echo "VERSION=v${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

      - name: Build and tag Pycharm devenv
        run: |
          docker build --no-cache -t lex_headless_pycharm:test -f ./build/DockerfilePycharm .
          docker tag lex_headless_pycharm:test europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_headless_pycharm:${{ env.VERSION }}

      - name: Push image
        run: |
          docker push --all-tags europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_headless_pycharm

  trigger-deploy-to-test:
    needs: [build-headless-pycharm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout instance-controller-deployment
        uses: actions/checkout@v2
        with:
          repository: LundIT/instance-controller-deployment
          token: ${{ secrets.PAT }}
          path: ./instance-controller-deployment
          ref: develop

      - name: Update dpag version in versions file
        uses: mikefarah/yq@master
        with:
          cmd: |
            VERSION=${{ needs.build-headless-pycharm.outputs.version}} yq -i '.lexDependencies.headlessPycharm = strenv(VERSION)' 'instance-controller-deployment/newest-versions.yaml'

      - name: Update version in versions file
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'touch temp.json && jq ".versions.lex_headless_pycharm = \"${{ needs.build-headless-pycharm.outputs.version}}\"" instance-controller-deployment/terraform/ic-test-application/versions.auto.tfvars.json > temp.json && mv temp.json instance-controller-deployment/terraform/ic-test-application/versions.auto.tfvars.json'

      - name: Push version update
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          cd instance-controller-deployment
          git pull
          git add terraform/ic-test-application/versions.auto.tfvars.json
          git commit -m "[Headless-Pycharm][$(git rev-parse --short "$GITHUB_SHA")] Push version ${{ needs.build-headless-pycharm.outputs.version }}"
          git pull
          git push origin develop
          ls -a
