name: ci-main-pycharm-push

on:
  push:
    tags:
      - "headless-pycharm-v*"

jobs:
  build-headless-pycharm:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION}}
    steps:
      - uses: actions/checkout@v2

      - id: "gcloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          create_credentials_file: false

      # This example uses the docker login action
      - uses: "docker/login-action@v1"
        with:
          registry: "europe-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.gcloud-auth.outputs.access_token }}"

      - name: Read and output sha
        id: version
        run: |
          echo "VERSION=v${GITHUB_REF##*v}" >> $GITHUB_ENV
          echo "VERSION=v${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

      - name: Build and tag Pycharm devenv
        run: |
          docker build --no-cache -t lex_headless_pycharm:test -f ./build/DockerfilePycharm .
          docker tag lex_headless_pycharm:test europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_headless_pycharm:${{ env.VERSION }}

      - name: Push image
        run: |
          docker push --all-tags europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_headless_pycharm

  deploy-to-test:
    needs: [build-headless-pycharm]
    uses: LundIT/instance-controller-deployment/.github/workflows/provision-environment.yaml@develop
    with:
      lex_env: test
      versions_override: '{"lex_headless_pycharm":"${{ needs.build-headless-pycharm.outputs.version }}"}'
      versions_override_persist: true
    secrets: inherit
