name: Python Security Scan

on:
  schedule:
    - cron: '0 23 * * 0' # scheduled to run every Sunday at 23:00 PM
  workflow_dispatch: # allows the workflow to be triggered manually

jobs:
  python-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Python 3.8 and Tools
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo add-apt-repository ppa:deadsnakes/ppa --yes
        sudo apt-get install python3.8 python3.8-distutils python3.8-dev build-essential -y
        python3.8 -m pip install --upgrade pip bandit

    - name: Run Bandit for Code Security
      run: bandit -r . > bandit-report.txt || true

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.txt
